package solver

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/totalwindupflightsystems/off-by-one/internal/graph"
	"github.com/totalwindupflightsystems/off-by-one/internal/ingest"
)

// fakeRunner is a filesystem-based Runner for tests. It does not
// spawn bwrap, does not require a real pi-agent binary, and is
// safe for concurrent use.
//
// Each Create returns a fresh handle backed by a unique
// t.TempDir-equivalent (we use os.MkdirTemp under t.TempDir so
// the directory is auto-cleaned). The handle's WriteFile /
// ReadFile are direct filesystem ops; Exec writes stdout to a
// file and returns it. A `piagentScript` may be set on the runner
// to override the default behavior.
type fakeRunner struct {
	mu         sync.Mutex
	script     string
	piAgentDir string
}

type fakeHandle struct {
	root    string
	stdout  []byte
	execErr error
}

func newFakeRunner(t *testing.T, script string) *fakeRunner {
	t.Helper()
	dir := t.TempDir()
	piAgent := filepath.Join(dir, "pi-agent")
	// Default script: write a minimal solution.md, evidence.md,
	// and signatures.json. Tests can override via the `script`
	// arg to newFakeRunner to simulate failures.
	if script == "" {
		script = defaultFakePiAgent
	}
	if err := os.WriteFile(piAgent, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake pi-agent: %v", err)
	}
	return &fakeRunner{piAgentDir: dir, script: script}
}

const defaultFakePiAgent = `#!/bin/sh
# Default fake pi-agent: writes a minimal solution + evidence +
# signatures bundle based on flags.
PROBLEM=""
OUTPUT=""
EVIDENCE=""
SIGNATURES=""
MODEL="unknown"
while [ $# -gt 0 ]; do
  case "$1" in
    --problem-file) PROBLEM="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --evidence) EVIDENCE="$2"; shift 2 ;;
    --signatures) SIGNATURES="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    *) shift ;;
  esac
done
# Read the problem to extract a class.
CLASS="unknown"
if [ -f "$PROBLEM" ]; then
  CLASS=$(grep -o '"problem_class"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROBLEM" | head -1 | sed 's/.*"\(.*\)"/\1/')
fi
cat > "$OUTPUT" << EOF
# Solution for $CLASS
This is the auto-generated answer for the problem.
## Steps
1. Diagnose
2. Fix
3. Verify
EOF
cat > "$EVIDENCE" << EOF
# Evidence
Reproducer attached.
EOF
cat > "$SIGNATURES" << EOF
{
  "problem_class": "$CLASS",
  "description": "auto-generated by fake pi-agent",
  "environment": "docker",
  "language": "go",
  "version": "1.26",
  "model": "$MODEL"
}
EOF
exit 0
`

func (r *fakeRunner) Create(ctx context.Context, id string) (Handle, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	root, err := os.MkdirTemp(r.piAgentDir, "ws-*"+id+"-*")
	if err != nil {
		return nil, err
	}
	return &fakeHandle{root: root}, nil
}

func (h *fakeHandle) WriteFile(relPath string, data []byte) error {
	full := filepath.Join(h.root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, data, 0o644)
}

func (h *fakeHandle) ReadFile(relPath string) ([]byte, error) {
	return os.ReadFile(filepath.Join(h.root, relPath))
}

func (h *fakeHandle) Exec(ctx context.Context, name string, args, env []string) ([]byte, error) {
	// We don't actually exec the script. Instead, we mirror the
	// defaultFakePiAgent's behaviour by writing the same files
	// (because the test's runner already wrote the script but
	// we want to control the outcome).
	// For tests that want full control, the test sets h.execErr
	// and we just return that.
	if h.execErr != nil {
		return h.stdout, h.execErr
	}
	// Find the --output / --evidence / --signatures paths.
	output := ""
	evidence := ""
	signatures := ""
	model := "unknown"
	problem := ""
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--output":
			if i+1 < len(args) {
				output = args[i+1]
				i++
			}
		case "--evidence":
			if i+1 < len(args) {
				evidence = args[i+1]
				i++
			}
		case "--signatures":
			if i+1 < len(args) {
				signatures = args[i+1]
				i++
			}
		case "--model":
			if i+1 < len(args) {
				model = args[i+1]
				i++
			}
		case "--problem-file":
			if i+1 < len(args) {
				problem = args[i+1]
				i++
			}
		}
	}
	// Translate /workspace/... paths to the workspace root.
	// Inside bwrap the workspace is mounted at /workspace; in
	// the fake, paths point at our local temp dir directly.
	readProblem := stripWorkspace(problem)
	output = stripWorkspace(output)
	evidence = stripWorkspace(evidence)
	signatures = stripWorkspace(signatures)
	class := "unknown"
	if readProblem != "" {
		if data, err := h.ReadFile(readProblem); err == nil {
			class = extractClassFromProblem(data)
		}
	}
	if output != "" {
		_ = h.WriteFile(output, []byte(fmt.Sprintf("# Solution for %s\nAuto-generated.\n", class)))
	}
	if evidence != "" {
		_ = h.WriteFile(evidence, []byte("# Evidence\nauto-generated.\n"))
	}
	if signatures != "" {
		_ = h.WriteFile(signatures, []byte(fmt.Sprintf(
			`{"problem_class":"%s","environment":"docker","language":"go","version":"1.26","model":"%s"}`,
			class, model)))
	}
	return []byte("fake pi-agent ok\n"), nil
}

func (h *fakeHandle) Destroy() error {
	if h.root == "" {
		return nil
	}
	err := os.RemoveAll(h.root)
	h.root = ""
	return err
}

func stripWorkspace(p string) string {
	if strings.HasPrefix(p, "/workspace/") {
		return strings.TrimPrefix(p, "/workspace/")
	}
	return p
}

func extractClassFromProblem(data []byte) string {
	var p struct {
		ProblemClass string `json:"problem_class"`
	}
	if err := json.Unmarshal(data, &p); err == nil && p.ProblemClass != "" {
		return p.ProblemClass
	}
	return "unknown"
}

// newTestSolver returns a solver wired to a fake runner and a
// fresh in-memory graph. Returns the solver, the store, and a
// cleanup function.
func newTestSolver(t *testing.T, script string) (*Executor, *graph.Store, *fakeRunner) {
	t.Helper()
	runner := newFakeRunner(t, script)
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-%s-%d", t.Name(), time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })
	cfg := Config{
		PiAgentPath: filepath.Join(runner.piAgentDir, "pi-agent"),
		Model:       "deepseek-v4-flash",
		APIKey:      "sk-test-key",
		Timeout:     5 * time.Second,
	}
	ex := NewExecutor(cfg, runner, store)
	return ex, store, runner
}

func sampleEntry(id string) *ingest.Entry {
	return &ingest.Entry{
		ID:           id,
		ProblemClass: "docker-cp-permission-denied",
		Environment:  "docker",
		Language:     "go",
		Version:      "1.26",
		Description:  "Permission denied when copying into container",
		ErrorMessage: "open /workspace/file: permission denied",
		StackTrace:   "main.go:42",
		Context:      map[string]any{"container": "alpine"},
		Cadence:      ingest.CadencePostDebug,
	}
}

func TestExecutor_Solve_HappyPath(t *testing.T) {
	ex, _, _ := newTestSolver(t, "")
	sol, err := ex.Solve(context.Background(), sampleEntry("sub-1"))
	if err != nil {
		t.Fatalf("Solve: %v", err)
	}
	if sol.SolutionMarkdown == "" {
		t.Error("solution.md content is empty")
	}
	if sol.EvidenceMarkdown == "" {
		t.Error("evidence.md content is empty")
	}
	if sol.Signatures == nil {
		t.Error("signatures is nil")
	}
	if sol.Signatures["problem_class"] != "docker-cp-permission-denied" {
		t.Errorf("signatures.problem_class = %v, want docker-cp-permission-denied",
			sol.Signatures["problem_class"])
	}
	if sol.Model != "deepseek-v4-flash" {
		t.Errorf("Model = %q, want deepseek-v4-flash", sol.Model)
	}
	if sol.DurationMS < 0 {
		t.Errorf("DurationMS = %d, want >= 0", sol.DurationMS)
	}
}

func TestExecutor_Solve_MissingBinary(t *testing.T) {
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-missing-%d", time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	defer store.Close()
	ex := NewExecutor(Config{PiAgentPath: "/nonexistent/pi-agent"}, nil, store)
	_, err = ex.Solve(context.Background(), sampleEntry("sub-x"))
	if !errors.Is(err, ErrPiAgentNotFound) {
		t.Errorf("err = %v, want ErrPiAgentNotFound", err)
	}
}

func TestExecutor_Solve_EmptyBinaryPath(t *testing.T) {
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-emptyp-%d", time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	defer store.Close()
	ex := NewExecutor(Config{}, nil, store)
	_, err = ex.Solve(context.Background(), sampleEntry("sub-y"))
	if !errors.Is(err, ErrPiAgentNotFound) {
		t.Errorf("err = %v, want ErrPiAgentNotFound", err)
	}
}

func TestExecutor_Solve_NilEntry(t *testing.T) {
	ex, _, _ := newTestSolver(t, "")
	_, err := ex.Solve(context.Background(), nil)
	if err == nil {
		t.Error("expected error for nil entry")
	}
}

func TestExecutor_Solve_ExecFailure(t *testing.T) {
	// Custom runner whose handle.Exec returns a fixed error.
	// We bypass the fakeRunner entirely so we don't need a
	// real pi-agent script.
	rec := &failingRunner{root: t.TempDir()}
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-fail-%d", time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	defer store.Close()
	ex := NewExecutor(Config{
		PiAgentPath: "/bin/true",
		Model:       "x",
		APIKey:      "",
		Timeout:     5 * time.Second,
	}, rec, store)
	_, err = ex.Solve(context.Background(), sampleEntry("sub-err"))
	if err == nil {
		t.Fatal("expected error from failing exec")
	}
	if !strings.Contains(err.Error(), "pi-agent exec") {
		t.Errorf("err = %v, want it to wrap pi-agent exec", err)
	}
}

// failingRunner returns a handle whose Exec always errors.
type failingRunner struct {
	root string
}

type failingHandle struct {
	root string
}

func (r *failingRunner) Create(ctx context.Context, id string) (Handle, error) {
	root, err := os.MkdirTemp(r.root, "fail-*"+id+"-*")
	if err != nil {
		return nil, err
	}
	return &failingHandle{root: root}, nil
}

func (h *failingHandle) WriteFile(relPath string, data []byte) error {
	full := filepath.Join(h.root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, data, 0o644)
}

func (h *failingHandle) ReadFile(relPath string) ([]byte, error) {
	return os.ReadFile(filepath.Join(h.root, relPath))
}

func (h *failingHandle) Exec(ctx context.Context, name string, args, env []string) ([]byte, error) {
	return []byte("partial output\n"), errors.New("simulated pi-agent failure")
}

func (h *failingHandle) Destroy() error {
	if h.root == "" {
		return nil
	}
	err := os.RemoveAll(h.root)
	h.root = ""
	return err
}

func TestExecutor_Solve_MissingSolution(t *testing.T) {
	// Custom script that exits 0 but does NOT write solution.md.
	script := "#!/bin/sh\nexit 0\n"
	ex, _, _ := newTestSolver(t, script)
	// The fakeHandle.Exec does not consult `script` — it always
	// writes the files. So we need a different approach: a
	// runner whose handle doesn't write any files at all.
	runner := &noWriteRunner{root: t.TempDir()}
	ex.runner = runner
	_, err := ex.Solve(context.Background(), sampleEntry("sub-missing"))
	if !errors.Is(err, ErrSolutionMissing) {
		t.Errorf("err = %v, want ErrSolutionMissing", err)
	}
}

// noWriteRunner is a Runner whose handle never writes any
// output files. Used to simulate "pi-agent ran but didn't produce
// solution.md".
type noWriteRunner struct {
	root string
}

func (r *noWriteRunner) Create(ctx context.Context, id string) (Handle, error) {
	root, err := os.MkdirTemp(r.root, "nowrite-*"+id+"-*")
	if err != nil {
		return nil, err
	}
	return &noWriteHandle{root: root}, nil
}

type noWriteHandle struct {
	root string
}

func (h *noWriteHandle) WriteFile(relPath string, data []byte) error {
	full := filepath.Join(h.root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, data, 0o644)
}

func (h *noWriteHandle) ReadFile(relPath string) ([]byte, error) {
	return os.ReadFile(filepath.Join(h.root, relPath))
}

func (h *noWriteHandle) Exec(ctx context.Context, name string, args, env []string) ([]byte, error) {
	// Pretend to run but don't write anything to the workspace.
	return []byte("silent\n"), nil
}

func (h *noWriteHandle) Destroy() error {
	if h.root == "" {
		return nil
	}
	err := os.RemoveAll(h.root)
	h.root = ""
	return err
}

func TestExecutor_Commit_StoresAnswer(t *testing.T) {
	ex, store, _ := newTestSolver(t, "")
	sol, err := ex.Solve(context.Background(), sampleEntry("sub-commit"))
	if err != nil {
		t.Fatalf("Solve: %v", err)
	}
	answerID, err := ex.Commit(context.Background(), sampleEntry("sub-commit"), sol)
	if err != nil {
		t.Fatalf("Commit: %v", err)
	}
	if answerID == 0 {
		t.Error("answerID = 0")
	}
	// Verify the row exists in the graph.
	answer, err := store.GetAnswerNode(context.Background(), answerID)
	if err != nil {
		t.Fatalf("GetAnswerNode: %v", err)
	}
	if answer.Solution != sol.SolutionMarkdown {
		t.Errorf("answer.Solution = %q, want %q", answer.Solution, sol.SolutionMarkdown)
	}
	if answer.Evidence != sol.EvidenceMarkdown {
		t.Errorf("answer.Evidence = %q, want %q", answer.Evidence, sol.EvidenceMarkdown)
	}
	if answer.Env != "docker" || answer.Lang != "go" || answer.Version != "1.26" {
		t.Errorf("answer scope = (%q, %q, %q), want (docker, go, 1.26)",
			answer.Env, answer.Lang, answer.Version)
	}
	// Status should be verified right after commit (MVP — validator ring deferred).
	if answer.Status != graph.AnswerVerified {
		t.Errorf("answer.Status = %q, want %q", answer.Status, graph.AnswerVerified)
	}
}

func TestExecutor_Commit_NilSolution(t *testing.T) {
	ex, _, _ := newTestSolver(t, "")
	_, err := ex.Commit(context.Background(), sampleEntry("nil"), nil)
	if err == nil {
		t.Error("expected error for nil solution")
	}
}

func TestExecutor_Commit_EmptySolution(t *testing.T) {
	ex, _, _ := newTestSolver(t, "")
	_, err := ex.Commit(context.Background(), sampleEntry("empty"), &Solution{})
	if err == nil {
		t.Error("expected error for empty solution")
	}
}

func TestResolveConfig_Defaults(t *testing.T) {
	cfg := ResolveConfig(Config{})
	if cfg.Model != DefaultModel {
		t.Errorf("Model = %q, want %q", cfg.Model, DefaultModel)
	}
	if cfg.Timeout != DefaultSolveTimeout {
		t.Errorf("Timeout = %v, want %v", cfg.Timeout, DefaultSolveTimeout)
	}
}

func TestResolveConfig_PreservesValues(t *testing.T) {
	cfg := ResolveConfig(Config{
		Model:   "custom-model",
		Timeout: 30 * time.Second,
	})
	if cfg.Model != "custom-model" {
		t.Errorf("Model = %q, want custom-model", cfg.Model)
	}
	if cfg.Timeout != 30*time.Second {
		t.Errorf("Timeout = %v, want 30s", cfg.Timeout)
	}
}

func TestExtractProblemClass_FromSignatures(t *testing.T) {
	sol := &Solution{
		Signatures: map[string]any{
			"problem_class": "my-class",
			"description":   "my-desc",
		},
	}
	title, desc := extractProblemClass(sol)
	if title != "my-class" {
		t.Errorf("title = %q, want my-class", title)
	}
	if desc != "my-desc" {
		t.Errorf("desc = %q, want my-desc", desc)
	}
}

func TestExtractProblemClass_Fallback(t *testing.T) {
	sol := &Solution{
		SolutionMarkdown: "# Header\n\nThis is the first paragraph.\n\nMore text.\n",
	}
	title, _ := extractProblemClass(sol)
	if title != "unknown" {
		t.Errorf("title = %q, want unknown", title)
	}
}

func TestExtractEnvFromSigs_Defaults(t *testing.T) {
	sol := &Solution{}
	env, lang, version := extractEnvFromSigs(sol)
	if env != "docker" || lang != "go" || version != "latest" {
		t.Errorf("env/lang/version = (%q, %q, %q), want (docker, go, latest)",
			env, lang, version)
	}
}

func TestExtractEnvFromSigs_FromSignatures(t *testing.T) {
	sol := &Solution{
		Signatures: map[string]any{
			"environment": "k8s",
			"language":    "python",
			"version":     "3.11",
		},
	}
	env, lang, version := extractEnvFromSigs(sol)
	if env != "k8s" {
		t.Errorf("env = %q, want k8s", env)
	}
	if lang != "python" {
		t.Errorf("lang = %q, want python", lang)
	}
	if version != "3.11" {
		t.Errorf("version = %q, want 3.11", version)
	}
}

func TestFirstParagraph(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"simple", "# Header\n\nFirst line.\n\nMore.\n", "First line."},
		{"empty", "", ""},
		{"no-header", "Real line\nMore", "Real line"},
		{"long-truncates", strings.Repeat("a", 250), strings.Repeat("a", 200)},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := firstParagraph(tt.in)
			if got != tt.want {
				t.Errorf("firstParagraph(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestTruncate(t *testing.T) {
	if got := truncate("hello", 10); got != "hello" {
		t.Errorf("truncate short = %q, want hello", got)
	}
	if got := truncate("hello world", 5); got != "hello…[truncated]" {
		t.Errorf("truncate long = %q, want hello…[truncated]", got)
	}
}

func TestExecutor_Solve_PropagatesAPIVars(t *testing.T) {
	// Custom runner that records the env passed to Exec.
	rec := &recordingRunner{root: t.TempDir()}
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-env-%d", time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	defer store.Close()
	ex := NewExecutor(Config{
		PiAgentPath: "/bin/true",
		Model:       "deepseek-v4-flash",
		APIKey:      "sk-test-key-1234",
		Timeout:     5 * time.Second,
	}, rec, store)
	_, _ = ex.Solve(context.Background(), sampleEntry("sub-env"))
	rec.mu.Lock()
	defer rec.mu.Unlock()
	// The handle updates its OWN lastEnv (separate field from
	// the runner's lastEnv) — read it via the handle.
	if rec.lastHandle == nil {
		t.Fatal("Exec was not called")
	}
	// rec.mu and lastHandle.mu are the SAME pointer — we already
	// hold rec.mu, so we can read lastEnv without re-locking.
	env := rec.lastHandle.lastEnv
	if len(env) == 0 {
		t.Fatal("Exec was called with empty env")
	}
	hasKey := false
	for _, e := range env {
		if strings.HasPrefix(e, "DEEPSEEK_API_KEY=") {
			hasKey = true
		}
	}
	if !hasKey {
		t.Errorf("env did not include DEEPSEEK_API_KEY: %v", env)
	}
}

// recordingRunner records the env passed to its handle's Exec
// call. It uses a real filesystem so the test exercises the full
// Solve flow.
type recordingRunner struct {
	mu         sync.Mutex
	root       string
	lastHandle *recordingHandle
}

type recordingHandle struct {
	root    string
	lastEnv []string
	mu      *sync.Mutex
}

func (r *recordingRunner) Create(ctx context.Context, id string) (Handle, error) {
	root, err := os.MkdirTemp(r.root, "rec-*"+id+"-*")
	if err != nil {
		return nil, err
	}
	r.mu.Lock()
	r.lastHandle = &recordingHandle{root: root, mu: &r.mu}
	h := r.lastHandle
	r.mu.Unlock()
	return h, nil
}

func (h *recordingHandle) WriteFile(relPath string, data []byte) error {
	full := filepath.Join(h.root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, data, 0o644)
}

func (h *recordingHandle) ReadFile(relPath string) ([]byte, error) {
	return os.ReadFile(filepath.Join(h.root, relPath))
}

func (h *recordingHandle) Exec(ctx context.Context, name string, args, env []string) ([]byte, error) {
	h.mu.Lock()
	h.lastEnv = append([]string{}, env...)
	h.mu.Unlock()
	// Write a minimal solution to make Solve succeed.
	_ = h.WriteFile("solution.md", []byte("# Solved\nOK.\n"))
	_ = h.WriteFile("evidence.md", []byte("# Evidence\nOK.\n"))
	_ = h.WriteFile("signatures.json", []byte(`{"problem_class":"x"}`))
	return []byte("rec-ok\n"), nil
}

func (h *recordingHandle) Destroy() error {
	if h.root == "" {
		return nil
	}
	err := os.RemoveAll(h.root)
	h.root = ""
	return err
}

func TestExecutor_Solve_Concurrent(t *testing.T) {
	// Run N solves in parallel against independent handles.
	// This stresses the lock-free handoff between Solve() and
	// Commit() — we don't Commit, just Solve, so the graph is
	// untouched.
	ex, _, _ := newTestSolver(t, "")
	const n = 8
	var wg sync.WaitGroup
	errs := make([]error, n)
	for i := 0; i < n; i++ {
		i := i
		wg.Add(1)
		go func() {
			defer wg.Done()
			entry := sampleEntry(fmt.Sprintf("sub-conc-%d", i))
			_, err := ex.Solve(context.Background(), entry)
			errs[i] = err
		}()
	}
	wg.Wait()
	for i, e := range errs {
		if e != nil {
			t.Errorf("solve %d: %v", i, e)
		}
	}
}

func TestExecutor_Solve_ContextCanceled(t *testing.T) {
	// A runner whose Exec blocks on a channel, then unblocks
	// when the context is cancelled.
	rec := &blockingRunner{root: t.TempDir(), unblock: make(chan struct{})}
	store, err := graph.OpenShared(fmt.Sprintf("test-solver-ctx-%d", time.Now().UnixNano()))
	if err != nil {
		t.Fatalf("graph.OpenShared: %v", err)
	}
	defer store.Close()
	ex := NewExecutor(Config{
		PiAgentPath: "/bin/true",
		Model:       "x",
		Timeout:     10 * time.Second,
	}, rec, store)
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() {
		_, err := ex.Solve(ctx, sampleEntry("sub-ctx"))
		done <- err
	}()
	// Give the goroutine a moment to start, then cancel.
	time.Sleep(50 * time.Millisecond)
	cancel()
	select {
	case err := <-done:
		if err == nil {
			t.Error("expected error from cancelled context")
		}
	case <-time.After(2 * time.Second):
		t.Fatal("Solve did not return after cancel")
	}
}

type blockingRunner struct {
	root    string
	unblock chan struct{}
}

type blockingHandle struct {
	root    string
	unblock chan struct{}
}

func (r *blockingRunner) Create(ctx context.Context, id string) (Handle, error) {
	root, err := os.MkdirTemp(r.root, "block-*"+id+"-*")
	if err != nil {
		return nil, err
	}
	return &blockingHandle{root: root, unblock: r.unblock}, nil
}

func (h *blockingHandle) WriteFile(relPath string, data []byte) error {
	full := filepath.Join(h.root, relPath)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	return os.WriteFile(full, data, 0o644)
}

func (h *blockingHandle) ReadFile(relPath string) ([]byte, error) {
	return os.ReadFile(filepath.Join(h.root, relPath))
}

func (h *blockingHandle) Exec(ctx context.Context, name string, args, env []string) ([]byte, error) {
	select {
	case <-h.unblock:
		return []byte(""), nil
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

func (h *blockingHandle) Destroy() error {
	if h.root == "" {
		return nil
	}
	err := os.RemoveAll(h.root)
	h.root = ""
	return err
}
